#!/usr/bin/env bash
#
# nixos-desktop-tmpl installer.
#
# Bootstraps a fresh NixOS machine into the niri + noctalia + fcitx5-mozc
# desktop defined by this template. Intended to be run once, right after a
# stock NixOS USB install:
#
#     curl -fsSL https://raw.githubusercontent.com/mrsmsn/nixos-desktop-tmpl/main/install.sh | bash
#
# It clones the template, detects machine-specific values (user, host, state
# version, CPU vendor), regenerates vars.nix and the hardware configuration,
# commits them, and runs the first `nixos-rebuild switch`. Every step is
# idempotent: re-running the script is safe and converges to the same state.
#
# Sourcing with INSTALL_SH_LIB=1 defines the helpers without running main(),
# so they can be exercised individually by unit tests.
set -euo pipefail
trap 'echo "install failed at line $LINENO" >&2' ERR

# --- logging helpers ---------------------------------------------------------

log() { printf '==> %s\n' "$*"; }
abort() { printf 'error: %s\n' "$*" >&2; exit 1; }

# --- environment probes ------------------------------------------------------

# /etc/NIXOS is the marker file NixOS always drops. The path is injectable so
# tests can point it at a fixture instead of the real system file.
# shellcheck disable=SC2120  # argument is only injected from tests
_is_nixos() {
    [ -e "${1:-/etc/NIXOS}" ]
}

# True when a controlling TTY is reachable. Works even under `curl | bash`
# because it opens /dev/tty directly rather than testing stdin.
_probe_tty_available() {
    : < /dev/tty 2>/dev/null
}

# git wrapper: use a system git when present, otherwise borrow one from
# nixpkgs. A stock NixOS install has git, but the ephemeral `nix shell` path
# keeps the script self-contained when it does not.
run_git() {
    if command -v git >/dev/null 2>&1; then
        git "$@"
    else
        nix shell --extra-experimental-features 'nix-command flakes' nixpkgs#git -c git "$@"
    fi
}

# --- input resolution --------------------------------------------------------

# Resolve the template repository URL.
# Precedence: $1 (CLI arg) > $NIXOS_TMPL_REPO > interactive prompt > default.
resolve_repo_url() {
    local default_url="https://github.com/mrsmsn/nixos-desktop-tmpl"

    if [ -n "${1:-}" ]; then
        printf '%s' "$1"
        return 0
    fi
    if [ -n "${NIXOS_TMPL_REPO:-}" ]; then
        printf '%s' "${NIXOS_TMPL_REPO}"
        return 0
    fi
    if _probe_tty_available; then
        local reply=""
        printf 'Template repository URL [%s]: ' "${default_url}" > /dev/tty
        read -r reply < /dev/tty || reply=""
        if [ -n "${reply}" ]; then
            printf '%s' "${reply}"
            return 0
        fi
    fi
    printf '%s' "${default_url}"
}

# Resolve the clone target directory.
# Precedence: $NIXOS_TMPL_DIR > $HOME/nixos-config.
resolve_target_dir() {
    printf '%s' "${NIXOS_TMPL_DIR:-${HOME}/nixos-config}"
}

# --- detection (each returns a value on stdout; args injectable for tests) ----

detect_username() {
    printf '%s' "${1:-${USER:-}}"
}

# shellcheck disable=SC2120  # $1 is only injected from tests; production omits it
detect_hostname() {
    if [ -n "${1:-}" ]; then
        printf '%s' "$1"
        return 0
    fi
    hostname
}

# Extract the leading MAJOR.MINOR from `nixos-version` output
# (e.g. "25.11.20240101.abcdef (Warbler)" -> "25.11").
# Pass the version string as $1 to test without invoking nixos-version.
detect_state_version() {
    local raw="${1:-}"
    if [ -z "${raw}" ]; then
        raw="$(nixos-version 2>/dev/null || true)"
    fi
    printf '%s' "${raw}" | grep -oE '^[0-9]+\.[0-9]+' | head -n1
}

# Map the CPU vendor_id from /proc/cpuinfo to a nixos-hardware module selector.
# Pass a file path as $1 to feed a fixture (there is no /proc on macOS).
detect_cpu_vendor() {
    local cpuinfo="${1:-/proc/cpuinfo}"
    local vendor=""
    if [ -r "${cpuinfo}" ]; then
        vendor="$(awk -F': ' '/^vendor_id/ { print $2; exit }' "${cpuinfo}")"
    fi
    case "${vendor}" in
        GenuineIntel) printf 'intel' ;;
        AuthenticAMD) printf 'amd' ;;
        *)            printf 'other' ;;
    esac
}

# --- validation --------------------------------------------------------------

validate_username() {
    [[ "${1:-}" =~ ^[a-z_][a-z0-9_-]*$ ]]
}

validate_hostname() {
    [[ "${1:-}" =~ ^[A-Za-z0-9-]+$ ]]
}

validate_state_version() {
    [[ "${1:-}" =~ ^[0-9]+\.[0-9]+$ ]]
}

# --- vars.nix generation -----------------------------------------------------

# Print the full vars.nix for the given values. Detected/validated values need
# no escaping, so the file is regenerated wholesale rather than sed-patched.
# Args: username hostname stateVersion cpuVendor
render_vars_nix() {
    cat <<EOF
{
  # Machine-specific values generated by install.sh.
  # Re-run install.sh to regenerate, or edit by hand and \`just switch\`.
  username = "$1"; # login user (detected from \$USER)
  hostname = "$2"; # host name (detected from \`hostname\`)
  stateVersion = "$3"; # NixOS state version (detected from \`nixos-version\`)
  cpuVendor = "$4"; # "intel" | "amd" | "other" (detected from /proc/cpuinfo)
}
EOF
}

# --- main --------------------------------------------------------------------

main() {
    # 1. Guards.
    log "Checking preconditions"
    if ! _is_nixos; then
        abort "This installer only runs on NixOS (missing /etc/NIXOS marker)."
    fi
    if [ "${EUID:-$(id -u)}" -eq 0 ]; then
        abort "一般ユーザーで実行してください。sudo は内部で必要時に使います。 / Run as a normal user; sudo is invoked internally when needed."
    fi

    # 2. Resolve inputs.
    local repo_url target_dir
    repo_url="$(resolve_repo_url "${1:-}")"
    target_dir="$(resolve_target_dir)"
    log "Repository: ${repo_url}"
    log "Target dir: ${target_dir}"

    # 3. Clone (or reuse an existing checkout — idempotent).
    log "Preparing repository checkout"
    if [ -d "${target_dir}" ]; then
        if run_git -C "${target_dir}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
            log "Reusing existing git repository at ${target_dir} (no fetch)"
        elif [ -n "$(ls -A "${target_dir}" 2>/dev/null)" ]; then
            abort "${target_dir} exists, is not a git repository, and is not empty. Move it aside or set NIXOS_TMPL_DIR."
        else
            log "Cloning into empty directory ${target_dir}"
            run_git clone "${repo_url}" "${target_dir}"
        fi
    else
        log "Cloning ${repo_url} into ${target_dir}"
        run_git clone "${repo_url}" "${target_dir}"
    fi

    # 4. Detect and validate machine-specific values.
    log "Detecting machine-specific values"
    local username hostname state_version cpu_vendor
    username="$(detect_username)"
    # shellcheck disable=SC2119  # detect_hostname's arg is a test-only override
    hostname="$(detect_hostname)"
    state_version="$(detect_state_version)"
    cpu_vendor="$(detect_cpu_vendor)"

    validate_username "${username}" \
        || abort "Invalid username '${username}' (must match ^[a-z_][a-z0-9_-]*\$)."
    validate_hostname "${hostname}" \
        || abort "Invalid hostname '${hostname}' (must match ^[A-Za-z0-9-]+\$)."
    validate_state_version "${state_version}" \
        || abort "Could not determine NixOS state version from \`nixos-version\`."

    log "username=${username} hostname=${hostname} stateVersion=${state_version} cpuVendor=${cpu_vendor}"

    # 5. Regenerate vars.nix (skip the write when nothing changed).
    log "Writing vars.nix"
    local vars_file="${target_dir}/vars.nix"
    local new_vars
    new_vars="$(render_vars_nix "${username}" "${hostname}" "${state_version}" "${cpu_vendor}")"
    if [ -f "${vars_file}" ] && [ "$(cat "${vars_file}")" = "${new_vars}" ]; then
        log "vars.nix unchanged"
    else
        printf '%s\n' "${new_vars}" > "${vars_file}"
        log "vars.nix updated"
    fi

    # 6. Generate the hardware configuration and sanity-check it.
    log "Generating hardware configuration"
    local hw_file="${target_dir}/hosts/default/hardware-configuration.nix"
    mkdir -p "$(dirname "${hw_file}")"
    # The redirect is intentionally performed as the invoking user (who owns the
    # repo), not root; only the generator itself needs sudo.
    # shellcheck disable=SC2024
    if sudo nixos-generate-config --show-hardware-config > "${hw_file}" 2>/dev/null; then
        log "Captured hardware config via nixos-generate-config"
    else
        log "nixos-generate-config failed; falling back to /etc/nixos/hardware-configuration.nix"
        if [ -r /etc/nixos/hardware-configuration.nix ]; then
            cat /etc/nixos/hardware-configuration.nix > "${hw_file}"
        else
            abort "Could not obtain a hardware configuration (no generator output and no /etc/nixos fallback)."
        fi
    fi
    # A stub without fileSystems would produce an unbootable system, so refuse
    # to proceed unless real mount points are present.
    if ! grep -q 'fileSystems' "${hw_file}"; then
        abort "Hardware configuration has no fileSystems entry; refusing to continue (would break boot)."
    fi

    # 7. Commit machine-specific changes (pure flakes ignore untracked files).
    log "Committing machine-specific configuration"
    if [ -n "$(run_git -C "${target_dir}" status --porcelain)" ]; then
        run_git -C "${target_dir}" add -A
        run_git -C "${target_dir}" \
            -c user.name="nixos-desktop-tmpl installer" \
            -c user.email="installer@localhost" \
            commit -m "init: machine-specific configuration"
        log "Committed"
    else
        log "No changes to commit"
    fi

    # 8. First rebuild. NIX_CONFIG is injected because the system-level
    #    experimental-features are not active until this switch lands.
    log "Running nixos-rebuild switch (this can take a while)"
    sudo env NIX_CONFIG="experimental-features = nix-command flakes" \
        nixos-rebuild switch --flake "${target_dir}#${hostname}"

    # 9. Done.
    log "Installation complete"
    cat <<EOF

  Reboot to reach the graphical login: noctalia-greeter appears and, on
  sign-in, starts the niri session.

  Day-2 operations:
    cd ${target_dir}
    just switch      # apply local edits
    just update      # bump flake inputs, then switch

  Your config lives in ${target_dir}. Edit vars.nix / modules / dotfiles
  there and re-run \`just switch\`.
EOF
}

if [ "${INSTALL_SH_LIB:-0}" != "1" ]; then
    main "$@"
fi
