export XDG_CONFIG_HOME=$HOME/.config

source "$XDG_CONFIG_HOME/zsh/env.zsh"
source "$XDG_CONFIG_HOME/zsh/aliases.zsh"
source "$XDG_CONFIG_HOME/zsh/functions.zsh"
source "$XDG_CONFIG_HOME/zsh/keybindings.zsh"
source "$XDG_CONFIG_HOME/zsh/tmux.zsh"
source "$XDG_CONFIG_HOME/zsh/init.zsh"
